---
- name: first playbook
  hosts: localhost
  become: true
  tasks:
  - name: ping the server
    ping:
  - name: print message
    debug: msg=addy
  - name: start httpd
    yum:
     name: httpd
     state: present
  - name: service start
    service:
      name: httpd
      state: started  
