---
- name: first playbook
  hosts: localhost
  tasks:
  - name: ping the server
    ping:
  - name: delete httpd
    yum:
     name: httpd
     state: absent
  - name: stop
    yum:
     name: httpd
     state: stopped
