---
- name: first playbook
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: ping the server
    ping:
  - name: print message
    debug: msg=addy
  - name: start httpd
    yum:
     name: httpd
     state: present
