---
- name: first playbook
  hosts: localhost
  tasks:
  - name: ping the server
    ping:
  - name: print message
    debug: msg=addy
  - name: stop
    service:
     name: httpd
     state: stopped
  - name: delete httpd
    yum:
     name: httpd
     state: absent
